# -*- coding: utf-8 -*-
"""face_emotion_realtime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ysvjTqQPC29vc_Eez1s0neeiazZVEMW
"""

import cv2

!pip install deepface

from deepface import DeepFace

from google.colab import files
uploaded = files.upload

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

cap = cv2.VideoCapture(1)

if not cap.isOpened():
  cap = cv2.VideoCapture(0)

if not cap.isOpened():
  raise IOError("Cannot open webcam")


while True:
  ret,frame = cap.read()

  result = DeepFace.analyze(frame, actions= ['emotion'])

  gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

  faces = faceCascade.detectMultiScale(gray,1.1,4)

  for x,y,w,h in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 2)

  font = cv2.FONT_HERSHEY_SIMPLEX

  cv2.putText(img,
              predictions['dominant_emotion'],
              (50,50),
              font,3,
              (0,0,255),
              2,
              cv2.LINE_4);
  cv2.imshow("Original Video", frame)

  if cv2.waitKey(2) & 0xFF == ord('q'):
    break

cap.release()
cv2.destroyAllWindows()

